---
name: QC Checking

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - dev
          - prod
      tag:
        type: string
        default: latest
  push:
    branches:
      - master
      - dev

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: Deploy Percobaan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout from repo
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: temurin
      - run: echo Ini Coba dulu ya  ${{ inputs }}
